<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\YumeArisu.Core\YumeArisu.Core.csproj" />
    <ProjectReference Include="..\YumeArisu.Game\YumeArisu.Game.csproj" />
    <PackageReference Include="Silk.NET.Windowing.Sdl" Version="2.23.0" />
    <PackageReference Include="Silk.NET.Input.Sdl" Version="2.23.0" />
  </ItemGroup>

  <PropertyGroup>
    <AssemblyName>YumeWoMiruArisu</AssemblyName>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <OutputType>WinExe</OutputType>
  </PropertyGroup>

  <PropertyGroup Condition="$(RuntimeIdentifier.StartsWith('win-'))">
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <IncludeAllContentForSelfExtract>true</IncludeAllContentForSelfExtract>
  </PropertyGroup>

  <PropertyGroup Condition="$(RuntimeIdentifier.StartsWith('linux-'))">
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <IncludeAllContentForSelfExtract>true</IncludeAllContentForSelfExtract>
  </PropertyGroup>

  <PropertyGroup Condition="$(RuntimeIdentifier.StartsWith('osx-'))">
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <IncludeAllContentForSelfExtract>true</IncludeAllContentForSelfExtract>
  </PropertyGroup>

  <Target Name="ExcludeSpecificDllsFromSingleFile" AfterTargets="ComputeResolvedFilesToPublishList">
    <ItemGroup>
      <ResolvedFileToPublish Update="@(ResolvedFileToPublish)"
                              Condition="'%(FileName)' == 'YumeArisu.Core' or '%(FileName)' == 'YumeArisu.Game'">
        <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
        <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      </ResolvedFileToPublish>
    </ItemGroup>
  </Target> 
  
</Project>